<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/getCancellationOption_Input_Map_req_1.map" md5sum="44907ac806dde0682ec50f3bd03bb307" version="8.0.501" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM Graphical Data Mapping Editor.
*   Version 8.0.5.0
*
*   Mapping file:		getCancellationOption_Input_Map_req_1.map
*   Map declaration(s):	getCancellationOption_Input_Map_req_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FTicketDomain-v1.0.0%252FRetrieveMasters%257DgetCancOptionRequestMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FAccess-ApplicationDB%252FDBInterface%257DretrieveallCancellationOptionBGRequestMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:str="http://exslt.org/strings"
    xmlns:exsl="http://exslt.org/common"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:in2="http://RACASBO"
    xmlns:in3="wsdl.http://TicketDomain-v1.0.0/RetrieveMasters"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io4="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io3="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io2="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:in="http://TicketDomain-v1.0.0/RetrieveMasters"
    xmlns:io="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:out343="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_draftupdateallinputbg"
    xmlns:out344="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detailbg"
    xmlns:out345="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ticketdetailsbg"
    xmlns:out346="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bulk_file_logupdateallinputbg"
    xmlns:out340="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_masterbg"
    xmlns:out341="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_user_details"
    xmlns:out342="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateexcessrefunddraftid"
    xmlns:out347="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/documentmatrixcontainer"
    xmlns:out348="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bank_detailslist"
    xmlns:out349="http://www.ibm.com/xmlns/prod/websphere/bo/6.0.0"
    xmlns:out334="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_draftcontainer"
    xmlns:out335="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_document_master"
    xmlns:out332="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_jobsbatchresult"
    xmlns:out333="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detailbatchresult"
    xmlns:out330="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_icrm_service_responsecontainer"
    xmlns:out331="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_valid_proposal_statusbatchresult"
    xmlns:out338="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_masterupdateallinputbg"
    xmlns:out339="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_jobslist"
    xmlns:out336="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_productlist"
    xmlns:out337="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_work_schedulelistbg"
    xmlns:out320="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_reverse_feed_status_masterupdateallinputbg"
    xmlns:out321="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_reasonlistbg"
    xmlns:out322="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/cancellationoptioncontainer"
    xmlns:out323="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/draftticketidcontainer"
    xmlns:out324="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bops_channel_ntid_configupdateallinput"
    xmlns:out325="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_lobcontainer"
    xmlns:out326="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_report_accessupdateallinput"
    xmlns:out327="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_productupdateallinputbg"
    xmlns:out328="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_receipt_detaillist"
    xmlns:out329="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approver"
    xmlns:out312="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updatedrafterrordetailsbg"
    xmlns:out313="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_work_scheduleupdateallinput"
    xmlns:out310="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_productupdateallinput"
    xmlns:out311="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_documentslist"
    xmlns:out316="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_optionbg"
    xmlns:out317="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_servicecontainer"
    xmlns:out314="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/gctransactionidcontainer"
    xmlns:out315="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_icrm_service_responsebatchresult"
    xmlns:out318="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_holiday_schedulecontainer"
    xmlns:out319="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/product"
    xmlns:out308="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_statuslist"
    xmlns:out307="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_reverse_feed_status_masterlistbg"
    xmlns:out309="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/productbg"
    xmlns:out304="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_masterupdateallinput"
    xmlns:out303="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_reverse_feedlistbg"
    xmlns:out401="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticketcontainer"
    xmlns:out306="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bops_channel_ntid_configcontainer"
    xmlns:out400="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_holiday_schedulelistbg"
    xmlns:out305="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_insuredlistbg"
    xmlns:out403="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_statusupdateallinputbg"
    xmlns:out300="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_lobupdateallinput"
    xmlns:out402="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_error_code_masterlistbg"
    xmlns:out405="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_icrm_service_responseupdateallinputbg"
    xmlns:out302="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_reverse_feed_status_masterupdateallinput"
    xmlns:out404="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/policydetailsbg"
    xmlns:out301="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_draft"
    xmlns:out406="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approverlist"
    xmlns:out101="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_insuredbatchresult"
    xmlns:out204="http://Access-ApplicationDB/DBInterface"
    xmlns:out102="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticketupdateallinputbg"
    xmlns:out205="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_reverse_feedcontainer"
    xmlns:out103="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refunddetails"
    xmlns:out206="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_app_configlist"
    xmlns:out104="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/cancellationreasonbg"
    xmlns:out207="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detail_histupdateallinputbg"
    xmlns:out208="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_productbg"
    xmlns:out209="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_draftlistbg"
    xmlns:out100="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_exception_histcontainer"
    xmlns:out109="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_productcontainer"
    xmlns:out105="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detailcontainer"
    xmlns:out200="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bulk_file_loglistbg"
    xmlns:out106="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_service"
    xmlns:out201="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_work_schedulelist"
    xmlns:out107="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_servicelist"
    xmlns:out202="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_receipt_detailbg"
    xmlns:out108="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_loblist"
    xmlns:out203="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_error_code_mastercontainer"
    xmlns:out226="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_user_detailscontainer"
    xmlns:out227="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/gctransactiondetails"
    xmlns:out228="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_histbatchresult"
    xmlns:out229="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_scheduler_statusbatchresult"
    xmlns:out222="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_receipt_detail"
    xmlns:out223="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_masterlistbg"
    xmlns:out224="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_valid_proposal_statuslist"
    xmlns:out225="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_error_code_masterbg"
    xmlns:out220="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateexcessrefunddraftbg"
    xmlns:out221="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/appconfigcontainer"
    xmlns:out219="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_statuscontainer"
    xmlns:out217="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_exception_histbatchresult"
    xmlns:out218="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_draftupdateallinput"
    xmlns:out215="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detail_histlistbg"
    xmlns:out216="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refundupdateallinput"
    xmlns:out213="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_documentsbatchresult"
    xmlns:out214="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bops_channel_ntid_configlist"
    xmlns:out211="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_report_accessupdateallinputbg"
    xmlns:out212="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_jobsbg"
    xmlns:out210="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approval_gridlistbg"
    xmlns:out11="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_jobs"
    xmlns:out12="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bopschannelntidconfigcontainer"
    xmlns:out10="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_option"
    xmlns:out19="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_reasonupdateallinput"
    xmlns:out18="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/draftticketbg"
    xmlns:out17="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refund_histupdateallinputbg"
    xmlns:out16="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_insuredupdateallinput"
    xmlns:out15="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_document_masterupdateallinput"
    xmlns:out14="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_exception_histupdateallinput"
    xmlns:out13="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/accountdetailscontainer"
    xmlns:out7="http://com/ibm/j2ca/fault"
    xmlns:out6="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/cancellationoptionbg"
    xmlns:out9="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_uploaded_filecontainer"
    xmlns:out8="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_holiday_scheduleupdateallinput"
    xmlns:out48="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_uploaded_filebg"
    xmlns:out3="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bops_channel_ntid_configlistbg"
    xmlns:out2="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refund_histcontainer"
    xmlns:out49="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bulk_file_logbg"
    xmlns:out46="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/reversefeed"
    xmlns:out5="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_exception_histupdateallinputbg"
    xmlns:out47="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_reasonupdateallinputbg"
    xmlns:out4="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bankdetails"
    xmlns:out41="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refund_histupdateallinput"
    xmlns:out40="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/appconfig"
    xmlns:out45="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateappconfig"
    xmlns:out199="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refund_histlist"
    xmlns:out44="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_document_masterbatchresult"
    xmlns:out198="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/reversefeedidcontainer"
    xmlns:out43="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_valid_proposal_statusbg"
    xmlns:out197="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_exception_histlistbg"
    xmlns:out42="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_optioncontainer"
    xmlns:out196="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticketlistbg"
    xmlns:out57="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/draftnocontainer"
    xmlns:out58="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_reasoncontainer"
    xmlns:out59="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_error_code_master"
    xmlns:out50="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_scheduler_status"
    xmlns:out52="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/cancellationreason"
    xmlns:out51="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_user_detailsbatchresult"
    xmlns:out54="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/reversefeedstatuscontainer"
    xmlns:out53="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_valid_proposal_statusupdateallinput"
    xmlns:out56="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_transactionbg"
    xmlns:out55="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_uploaded_file"
    xmlns:out28="http://com/ibm/j2ca/fault/afcfault"
    xmlns:out29="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detail_histbg"
    xmlns:out26="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_report_accessbg"
    xmlns:out27="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_transactionlistbg"
    xmlns:out24="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_reasonbg"
    xmlns:out25="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_user_detailsbg"
    xmlns:out23="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ticketdetailscontainer"
    xmlns:out22="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bank_detailscontainer"
    xmlns:out21="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_valid_proposal_statuscontainer"
    xmlns:out20="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/receiptdetailscontainer"
    xmlns:out39="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approverupdateallinputbg"
    xmlns:out35="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_error_code_masterlist"
    xmlns:out36="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_documents"
    xmlns:out37="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_transactionupdateallinput"
    xmlns:out38="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_work_schedulebg"
    xmlns:out32="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detail_histlist"
    xmlns:out31="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_hist"
    xmlns:out34="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bank_detailslistbg"
    xmlns:out33="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_jobsupdateallinputbg"
    xmlns:out30="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bankdetailscontainer"
    xmlns:out80="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_app_configbatchresult"
    xmlns:out81="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticketlist"
    xmlns:out84="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket"
    xmlns:out85="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approval_gridcontainer"
    xmlns:out82="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detail_histbatchresult"
    xmlns:out83="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refund_histlistbg"
    xmlns:out88="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_jobslistbg"
    xmlns:out89="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_exception_histlist"
    xmlns:out86="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_icrm_service_responselist"
    xmlns:out87="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bulk_file_logbatchresult"
    xmlns:out90="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_report_access"
    xmlns:out91="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_productlistbg"
    xmlns:out92="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_uploaded_filelist"
    xmlns:out93="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_policy_detailupdateallinput"
    xmlns:out94="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/reversefeedidbg"
    xmlns:out95="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_servicebg"
    xmlns:out96="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_policy_detail"
    xmlns:out97="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_draftbatchresult"
    xmlns:out98="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticketupdateallinput"
    xmlns:out99="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_insuredcontainer"
    xmlns:out69="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/gctransactionid"
    xmlns:out68="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approval_gridupdateallinput"
    xmlns:out66="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_work_scheduleupdateallinputbg"
    xmlns:out67="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_mastercontainer"
    xmlns:out64="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_optionbatchresult"
    xmlns:out65="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bops_channel_ntid_configbatchresult"
    xmlns:out62="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_error_code_masterupdateallinputbg"
    xmlns:out63="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/reversefeedbg"
    xmlns:out60="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refundbg"
    xmlns:out61="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/draftidbg"
    xmlns:out79="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_app_configbg"
    xmlns:out70="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_reverse_feed_status_masterlist"
    xmlns:out75="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateexcessrefundreversefeed"
    xmlns:out76="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bops_channel_ntid_configbg"
    xmlns:out77="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refundupdateallinputbg"
    xmlns:out78="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_reverse_feed_status_masterbg"
    xmlns:out71="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_policy_detailbatchresult"
    xmlns:out72="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approval_grid"
    xmlns:out73="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_transactionlist"
    xmlns:out="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_app_configcontainer"
    xmlns:out74="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_reverse_feed_status_master"
    xmlns:out113="wsdl.http://Access-ApplicationDB/DBInterface"
    xmlns:out112="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_work_schedulebatchresult"
    xmlns:out115="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_report_accesslistbg"
    xmlns:out114="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateexcessrefunddraft"
    xmlns:out111="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_user_detailslistbg"
    xmlns:out110="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_servicebatchresult"
    xmlns:out117="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updatedrafterrordetails"
    xmlns:out116="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_masterlist"
    xmlns:out119="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_scheduler_statuslist"
    xmlns:out118="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detail"
    xmlns:out295="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_draftbg"
    xmlns:out296="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateexcessrefundservice"
    xmlns:out297="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/draftticketcontainer"
    xmlns:out298="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refunddetailscontainer"
    xmlns:out299="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detaillist"
    xmlns:out398="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_document_masterupdateallinputbg"
    xmlns:out399="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_reverse_feed"
    xmlns:out394="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refundlistbg"
    xmlns:out395="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_reverse_feedupdateallinputbg"
    xmlns:out396="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refundlist"
    xmlns:out397="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_receipt_detailcontainer"
    xmlns:out126="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/accountdetailsbg"
    xmlns:out125="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/documentmatrixbg"
    xmlns:out124="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_reasonbatchresult"
    xmlns:out123="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_productbatchresult"
    xmlns:out122="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_histlistbg"
    xmlns:out121="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_loblistbg"
    xmlns:out120="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bank_detailsbg"
    xmlns:out129="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_histupdateallinputbg"
    xmlns:out128="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bank_details"
    xmlns:out127="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_documentslistbg"
    xmlns:out131="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/cancellationoption"
    xmlns:out130="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_masterbatchresult"
    xmlns:out133="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ticketdetails"
    xmlns:out132="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updategctransactiondetails"
    xmlns:out135="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_scheduler_statuscontainer"
    xmlns:out134="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/reversefeedstatusbg"
    xmlns:out137="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_reverse_feedbatchresult"
    xmlns:out136="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_transactionupdateallinputbg"
    xmlns:out139="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_report_accesscontainer"
    xmlns:out281="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_insuredlist"
    xmlns:out138="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_exception_histbg"
    xmlns:out280="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/lobcontainer"
    xmlns:out283="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_documentsupdateallinputbg"
    xmlns:out282="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_user_detailsupdateallinput"
    xmlns:out277="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_documentsbg"
    xmlns:out278="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/policydetails"
    xmlns:out279="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_lobupdateallinputbg"
    xmlns:out273="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approvercontainer"
    xmlns:out274="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/reversefeedcontainer"
    xmlns:out275="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_statusbg"
    xmlns:out276="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_serviceupdateallinput"
    xmlns:out140="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/gctransactionidbg"
    xmlns:out144="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approverupdateallinput"
    xmlns:out143="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateappconfigbg"
    xmlns:out142="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_insured"
    xmlns:out141="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticketbatchresult"
    xmlns:out148="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_valid_proposal_statusupdateallinputbg"
    xmlns:out147="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_reason"
    xmlns:out146="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_reasonlist"
    xmlns:out145="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_holiday_scheduleupdateallinputbg"
    xmlns:out294="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_jobscontainer"
    xmlns:out293="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_histcontainer"
    xmlns:out292="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/draftidcontainer"
    xmlns:out149="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bopschannelntidconfigbg"
    xmlns:out291="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_reverse_feed_status_masterbatchresult"
    xmlns:out290="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_master"
    xmlns:out288="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_documentsupdateallinput"
    xmlns:out289="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/serviceidcontainer"
    xmlns:out286="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_lobbg"
    xmlns:out287="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/reversefeedstatus"
    xmlns:out284="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_user_detailslist"
    xmlns:out285="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/serviceid"
    xmlns:out150="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bank_detailsupdateallinput"
    xmlns:out151="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_uploaded_fileupdateallinput"
    xmlns:out260="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bank_detailsupdateallinputbg"
    xmlns:out261="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/gctransactiondetailsbg"
    xmlns:out156="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_serviceupdateallinputbg"
    xmlns:out157="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updatetransactioncountbg"
    xmlns:out158="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/gctransactiondetailscontainer"
    xmlns:out159="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateappcongfigslno"
    xmlns:out360="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_optionupdateallinputbg"
    xmlns:out152="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_error_code_masterbatchresult"
    xmlns:out153="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refund_histbg"
    xmlns:out154="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_work_schedule"
    xmlns:out155="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bulk_file_logcontainer"
    xmlns:out160="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_scheduler_statuslistbg"
    xmlns:out355="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_jobsupdateallinput"
    xmlns:out259="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_transactionbatchresult"
    xmlns:out354="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_statusbatchresult"
    xmlns:out162="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_uploaded_filebatchresult"
    xmlns:out357="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateexcessrefundreversefeedbg"
    xmlns:out161="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refund_histbatchresult"
    xmlns:out356="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_icrm_service_response"
    xmlns:out351="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bulk_file_logupdateallinput"
    xmlns:out350="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/lob"
    xmlns:out353="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/draftticketidbg"
    xmlns:out352="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approval_gridbatchresult"
    xmlns:out252="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bulk_file_log"
    xmlns:out251="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_reverse_feedupdateallinput"
    xmlns:out254="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approverbatchresult"
    xmlns:out253="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_uploaded_filelistbg"
    xmlns:out256="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detail_hist"
    xmlns:out359="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_histbg"
    xmlns:out255="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_status"
    xmlns:out358="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_valid_proposal_status"
    xmlns:out258="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_document_masterbg"
    xmlns:out257="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detailupdateallinputbg"
    xmlns:out271="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bankdetailsbg"
    xmlns:out272="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_optionlist"
    xmlns:out270="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_documentscontainer"
    xmlns:out169="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateappcongfigslnobg"
    xmlns:out370="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_app_config"
    xmlns:out371="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approval_gridupdateallinputbg"
    xmlns:out167="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateexcessrefunddraftidbg"
    xmlns:out168="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_reverse_feed_status_mastercontainer"
    xmlns:out165="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_holiday_schedulelist"
    xmlns:out166="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/accountdetails"
    xmlns:out163="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_report_accesslist"
    xmlns:out164="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bulk_file_loglist"
    xmlns:out173="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_receipt_detailbatchresult"
    xmlns:out368="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/draftid"
    xmlns:out172="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approverlistbg"
    xmlns:out367="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approval_gridlist"
    xmlns:out171="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticketbg"
    xmlns:out366="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_scheduler_statusbg"
    xmlns:out170="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/draftticketid"
    xmlns:out365="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_transactioncontainer"
    xmlns:out364="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/productcontainer"
    xmlns:out363="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bops_channel_ntid_configupdateallinputbg"
    xmlns:out362="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/draftticket"
    xmlns:out361="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_histupdateallinput"
    xmlns:out265="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_optionlistbg"
    xmlns:out264="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_lobbatchresult"
    xmlns:out263="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_policy_detailupdateallinputbg"
    xmlns:out262="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_histlist"
    xmlns:out269="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/draftno"
    xmlns:out268="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_work_schedulecontainer"
    xmlns:out267="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_uploaded_fileupdateallinputbg"
    xmlns:out266="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_draftlist"
    xmlns:out369="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_receipt_detaillistbg"
    xmlns:out174="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approverbg"
    xmlns:out175="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detail_histcontainer"
    xmlns:out176="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/receiptdetails"
    xmlns:out177="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refundcontainer"
    xmlns:out178="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_app_configupdateallinput"
    xmlns:out380="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_statusupdateallinput"
    xmlns:out179="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_user_detailsupdateallinputbg"
    xmlns:out381="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detail_histupdateallinput"
    xmlns:out382="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateexcessrefundservicebg"
    xmlns:out373="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/policydetailscontainer"
    xmlns:out372="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_receipt_detailupdateallinput"
    xmlns:out180="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_receipt_detailupdateallinputbg"
    xmlns:out375="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approval_gridbg"
    xmlns:out374="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_document_mastercontainer"
    xmlns:out182="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_document_masterlistbg"
    xmlns:out238="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_document_masterlist"
    xmlns:out377="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/cancellationreasoncontainer"
    xmlns:out181="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refundbatchresult"
    xmlns:out237="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/documentmatrix"
    xmlns:out376="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_icrm_service_responseupdateallinput"
    xmlns:out379="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bulkoperationresult/updateallresult"
    xmlns:out184="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_app_configupdateallinputbg"
    xmlns:out183="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_policy_detaillistbg"
    xmlns:out239="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_holiday_schedulebg"
    xmlns:out378="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_reverse_feedbg"
    xmlns:out234="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_holiday_schedule"
    xmlns:out233="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_app_configlistbg"
    xmlns:out236="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updategctransactiondetailsbg"
    xmlns:out235="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/receiptdetailsbg"
    xmlns:out230="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_insuredupdateallinputbg"
    xmlns:out232="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_statuslistbg"
    xmlns:out231="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/draftnobg"
    xmlns:out250="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bopschannelntidconfig"
    xmlns:out187="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/appconfigbg"
    xmlns:out188="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_policy_detailbg"
    xmlns:out185="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_scheduler_statusupdateallinput"
    xmlns:out186="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_report_accessbatchresult"
    xmlns:out392="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_holiday_schedulebatchresult"
    xmlns:out393="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_icrm_service_responsebg"
    xmlns:out390="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detaillistbg"
    xmlns:out189="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refund"
    xmlns:out391="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/reversefeedid"
    xmlns:out386="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_product"
    xmlns:out191="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refunddetailsbg"
    xmlns:out385="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_reverse_feedlist"
    xmlns:out190="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_insuredbg"
    xmlns:out384="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_valid_proposal_statuslistbg"
    xmlns:out383="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bops_channel_ntid_config"
    xmlns:out195="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bank_detailsbatchresult"
    xmlns:out389="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updatetransactioncount"
    xmlns:out194="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/existsresult/existsresult"
    xmlns:out388="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_transaction"
    xmlns:out193="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detailupdateallinput"
    xmlns:out249="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_optionupdateallinput"
    xmlns:out387="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refund_hist"
    xmlns:out192="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_icrm_service_responselistbg"
    xmlns:out248="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_servicelistbg"
    xmlns:out247="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_policy_detaillist"
    xmlns:out246="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/lobbg"
    xmlns:out245="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_policy_detailcontainer"
    xmlns:out244="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_lob"
    xmlns:out243="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_error_code_masterupdateallinput"
    xmlns:out242="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_scheduler_statusupdateallinputbg"
    xmlns:out241="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/serviceidbg"
    xmlns:out240="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_exception_hist"
    xmlns:out480="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateaccountdetailsbg"
    xmlns:out481="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementlobproductcontainer"
    xmlns:out471="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_service_loggingupdateallinputbg"
    xmlns:out472="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementproductname"
    xmlns:out473="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementdraftidcontainer"
    xmlns:out430="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementmastercontainer"
    xmlns:out474="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementloggingidbg"
    xmlns:out431="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateinsureddetails"
    xmlns:out475="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementproductcodebg"
    xmlns:out432="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updaterefunddetails"
    xmlns:out476="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/policydetailspolicynocertificatenocontainer"
    xmlns:out433="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateccmtransactiondeatils"
    xmlns:out477="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/insureddetailsbg"
    xmlns:out434="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/userdetails"
    xmlns:out478="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_draft_ticketupdateallinputbg"
    xmlns:out435="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/policydetailspolicynolannocontainer"
    xmlns:out479="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/policydetailspolicynoproposalno"
    xmlns:out436="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updatepolicydetailsbg"
    xmlns:out437="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updatenegativeendorsementdraftticketdetails"
    xmlns:out438="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ticketdetailsreceiptno"
    xmlns:out439="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_draft_ticketlistbg"
    xmlns:out490="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_service_loggingupdateallinput"
    xmlns:out491="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updatenegativeendorsementserviceloggingbg"
    xmlns:out492="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updaterefunddetailsbg"
    xmlns:out482="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateinsureddetailsbg"
    xmlns:out483="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/userdetailscontainer"
    xmlns:out440="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateticketstatusbg"
    xmlns:out484="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementdraftticketcontainer"
    xmlns:out441="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_service_loggingbatchresult"
    xmlns:out485="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updatenegativeendorsementservicelogging"
    xmlns:out442="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_service_loggingcontainer"
    xmlns:out486="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementlobcontainer"
    xmlns:out443="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementmasterbg"
    xmlns:out487="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updatereceiptdetailsbg"
    xmlns:out444="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/insureddetails"
    xmlns:out488="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementdraftnobg"
    xmlns:out445="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/userdetailsbg"
    xmlns:out489="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updatenegativeendorsementdraftticketdetailsbg"
    xmlns:out446="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ticketdetailspolicyno"
    xmlns:out447="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementloggingidcontainer"
    xmlns:out448="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ccmrequestid"
    xmlns:out449="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_draft_ticketupdateallinput"
    xmlns:out407="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_service_loggingbg"
    xmlns:out408="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementloggingid"
    xmlns:out409="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ticketdetailspolicynocontainer"
    xmlns:out493="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementmaster"
    xmlns:out450="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementdraftticketbg"
    xmlns:out494="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ticketdetailsreceiptnobg"
    xmlns:out451="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateticketdetailsbg"
    xmlns:out495="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementdraftid"
    xmlns:out452="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateccmtransactiondeatilsbg"
    xmlns:out496="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/policydetailspolicynocertificateno"
    xmlns:out453="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ticketdetailspolicynoapplicationnobg"
    xmlns:out497="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementproductcodecontainer"
    xmlns:out410="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementdraftidbg"
    xmlns:out454="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ticketdetailspolicynoapplicationnocontainer"
    xmlns:out498="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_draft_ticketcontainer"
    xmlns:out411="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ticketdetailspolicynoapplicationno"
    xmlns:out455="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementlobproduct"
    xmlns:out499="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/policydetailspolicynolannobg"
    xmlns:out412="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_draft_ticket"
    xmlns:out456="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementlob"
    xmlns:out413="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/policydetailspolicynocertificatenobg"
    xmlns:out457="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementproductnamebg"
    xmlns:out414="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateaccountdetails"
    xmlns:out458="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/insureddetailscontainer"
    xmlns:out415="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/metadata"
    xmlns:out459="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementdraftticket"
    xmlns:out416="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updatepolicydetails"
    xmlns:out417="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementlobproductbg"
    xmlns:out418="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ccmrequestidcontainer"
    xmlns:out419="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/policydetailspolicynoproposalnobg"
    xmlns:out470="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ticketdetailsreceiptnocontainer"
    xmlns:out460="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ticketdetailspolicynobg"
    xmlns:out461="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ccmrequestidbg"
    xmlns:out462="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateticketdetailstatusbg"
    xmlns:out463="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_service_logginglist"
    xmlns:out420="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementlobbg"
    xmlns:out464="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementproductcode"
    xmlns:out421="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/policydetailspolicynoproposalnocontainer"
    xmlns:out465="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_service_logginglistbg"
    xmlns:out422="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateticketdetailstatus"
    xmlns:out466="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/policydetailspolicynolanno"
    xmlns:out423="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_draft_ticketbg"
    xmlns:out467="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_draft_ticketbatchresult"
    xmlns:out424="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updatereceiptdetails"
    xmlns:out468="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementdraftno"
    xmlns:out425="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementdraftnocontainer"
    xmlns:out469="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_service_logging"
    xmlns:out426="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateticketstatus"
    xmlns:out427="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementproductnamecontainer"
    xmlns:out428="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_draft_ticketlist"
    xmlns:out429="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateticketdetails"
    xmlns:ToUpperCase="xalan://com.org.aig.tataaig.ToUpperCase"
    xmlns:map="http://RASAccess-ApplicationDB/xslt/getCancellationOption_Input_Map_req_1"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="date str exsl set math ToUpperCase map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'out113:retrieveallCancellationOptionBGRequestMsg'"/>
            </xsl:attribute>
            <xsl:call-template name="map:getCancellationOption_Input_Map_req_12">
              <xsl:with-param name="body" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="body" mode="map:getCancellationOption_Input_Map_req_1"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:getCancellationOption_Input_Map_req_1">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out113:retrieveallCancellationOptionBGRequestMsg'"/>
      </xsl:attribute>
      <out204:retrieveallCancellationOptionBG>
        <out204:retrieveallCancellationOptionBGInput>
          <CancellationOption>
            <!-- a simple data mapping: "in:getCancOption/lob"(string) to "lob"(string) -->
            <xsl:if test="in:getCancOption/lob">
              <xsl:element name="lob">
                <!-- variables for custom code -->
                <xsl:variable name="lob" select="in:getCancOption/lob"/>
                <xsl:value-of select="ToUpperCase:sampleTransform($lob)"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple mapping with no associated source:  to "is_active"(string) -->
            <xsl:element name="is_active">
              <xsl:text>Y</xsl:text>
            </xsl:element>
            <!-- a simple data mapping: "in:getCancOption/product"(string) to "product"(string) -->
            <xsl:if test="in:getCancOption/product">
              <xsl:choose>
                <xsl:when test="normalize-space(in:getCancOption/product)">
                  <xsl:element name="product">
                    <xsl:value-of select="in:getCancOption/product"/>
                  </xsl:element>
                </xsl:when>
                <xsl:otherwise>
                  <product xsi:nil="true"/>
                </xsl:otherwise>
              </xsl:choose>
            </xsl:if>
            <!-- a simple data mapping: "in:getCancOption/product"(string) to "parameter1"(string) -->
            <xsl:choose>
              <xsl:when test="normalize-space(in:getCancOption/product)">
                <xsl:element name="parameter1">
                  <xsl:value-of select="in:getCancOption/product"/>
                </xsl:element>
              </xsl:when>
              <xsl:otherwise>
                <parameter1 xsi:nil="true"/>
              </xsl:otherwise>
            </xsl:choose>
          </CancellationOption>
        </out204:retrieveallCancellationOptionBGInput>
      </out204:retrieveallCancellationOptionBG>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:getCancellationOption_Input_Map_req_12">
    <xsl:param name="body"/>
    <out204:retrieveallCancellationOptionBG>
      <out204:retrieveallCancellationOptionBGInput>
        <CancellationOption>
          <!-- a simple data mapping: "$body/in:getCancOption/lob"(string) to "lob"(string) -->
          <xsl:if test="$body/in:getCancOption/lob">
            <xsl:element name="lob">
              <!-- variables for custom code -->
              <xsl:variable name="lob" select="$body/in:getCancOption/lob"/>
              <xsl:value-of select="ToUpperCase:sampleTransform($lob)"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple mapping with no associated source:  to "is_active"(string) -->
          <xsl:element name="is_active">
            <xsl:text>Y</xsl:text>
          </xsl:element>
          <!-- a simple data mapping: "$body/in:getCancOption/product"(string) to "product"(string) -->
          <xsl:if test="$body/in:getCancOption/product">
            <xsl:choose>
              <xsl:when test="normalize-space($body/in:getCancOption/product)">
                <xsl:element name="product">
                  <xsl:value-of select="$body/in:getCancOption/product"/>
                </xsl:element>
              </xsl:when>
              <xsl:otherwise>
                <product xsi:nil="true"/>
              </xsl:otherwise>
            </xsl:choose>
          </xsl:if>
          <!-- a simple data mapping: "$body/in:getCancOption/product"(string) to "parameter1"(string) -->
          <xsl:choose>
            <xsl:when test="normalize-space($body/in:getCancOption/product)">
              <xsl:element name="parameter1">
                <xsl:value-of select="$body/in:getCancOption/product"/>
              </xsl:element>
            </xsl:when>
            <xsl:otherwise>
              <parameter1 xsi:nil="true"/>
            </xsl:otherwise>
          </xsl:choose>
        </CancellationOption>
      </out204:retrieveallCancellationOptionBGInput>
    </out204:retrieveallCancellationOptionBG>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
