<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/input_map_req_1.map" md5sum="ab969808403baf468f64ab8b2fcd9bae" version="8.0.501" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM Graphical Data Mapping Editor.
*   Version 8.0.5.0
*
*   Mapping file:		input_map_req_1.map
*   Map declaration(s):	input_map_req_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FTicketDomain-v1.0.0%252FRetrieveDocuments%257DfindAllDocumentsRequestMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FAccess-ApplicationDB%252FJDBCImport%257DretrieveRefundRas_Ticket_DocumentsBGRequestMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:str="http://exslt.org/strings"
    xmlns:exsl="http://exslt.org/common"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:in2="http://RACASBO"
    xmlns:in3="http://TicketDomain-v1.0.0/RetrieveDocuments"
    xmlns:io5="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:in="wsdl.http://TicketDomain-v1.0.0/RetrieveDocuments"
    xmlns:io="http://www.w3.org/2005/08/addressing"
    xmlns:out113="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_insuredlist"
    xmlns:out112="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_hist"
    xmlns:out115="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_jobsbg"
    xmlns:out114="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_documentslistbg"
    xmlns:out7="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticketbg"
    xmlns:out6="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detailupdateallinputbg"
    xmlns:out111="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_policy_detailupdateallinput"
    xmlns:out9="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_refundbg"
    xmlns:out110="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_reasonlist"
    xmlns:out8="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_document_master"
    xmlns:out3="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_exception_histupdateallinput"
    xmlns:out48="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_lobupdateallinputbg"
    xmlns:out2="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_documentsbatchresult"
    xmlns:out49="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_receipt_detailupdateallinput"
    xmlns:out5="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_reasoncontainer"
    xmlns:out46="http://www.ibm.com/xmlns/prod/websphere/bo/6.0.0"
    xmlns:out4="http://Access-ApplicationDB/JDBCImport"
    xmlns:out47="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_jobscontainer"
    xmlns:out117="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detailupdateallinput"
    xmlns:out116="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_loblistbg"
    xmlns:out119="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_document_masterupdateallinput"
    xmlns:out118="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_documentsupdateallinput"
    xmlns:out41="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_policy_detail"
    xmlns:out40="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_refundupdateallinput"
    xmlns:out45="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_insuredbatchresult"
    xmlns:out44="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_document_masterbatchresult"
    xmlns:out43="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_lobcontainer"
    xmlns:out42="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detaillistbg"
    xmlns:out126="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_jobs"
    xmlns:out125="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/documentu32matrix"
    xmlns:out124="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_lobbatchresult"
    xmlns:out123="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_app_configupdateallinput"
    xmlns:out122="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_optioncontainer"
    xmlns:out121="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_reasonlistbg"
    xmlns:out120="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_app_configupdateallinputbg"
    xmlns:out57="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_app_configbatchresult"
    xmlns:out58="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_optionbatchresult"
    xmlns:out59="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_histlistbg"
    xmlns:out129="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_histupdateallinput"
    xmlns:out128="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_lob"
    xmlns:out127="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_optionupdateallinputbg"
    xmlns:out50="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_histlist"
    xmlns:out52="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_reasonbg"
    xmlns:out51="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_approverbatchresult"
    xmlns:out54="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_app_configcontainer"
    xmlns:out53="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_loblist"
    xmlns:out56="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_reasonbatchresult"
    xmlns:out55="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_document_masterupdateallinputbg"
    xmlns:out131="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_jobsupdateallinput"
    xmlns:out130="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_document_masterlistbg"
    xmlns:out133="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_insuredlistbg"
    xmlns:out132="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_policy_detailupdateallinputbg"
    xmlns:out135="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_exception_histcontainer"
    xmlns:out134="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_reasonupdateallinput"
    xmlns:out137="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_app_config"
    xmlns:out136="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_exception_histbatchresult"
    xmlns:out139="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detailbatchresult"
    xmlns:out138="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_receipt_detaillistbg"
    xmlns:out28="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_histbatchresult"
    xmlns:out29="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_refund"
    xmlns:out26="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_receipt_detailbatchresult"
    xmlns:out27="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_documentsbg"
    xmlns:out24="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_exception_histbg"
    xmlns:out25="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_jobsupdateallinputbg"
    xmlns:out23="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detailbg"
    xmlns:out22="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticketupdateallinput"
    xmlns:out21="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_policy_detaillistbg"
    xmlns:out20="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_documents"
    xmlns:out140="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticketupdateallinputbg"
    xmlns:out144="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_policy_detailbg"
    xmlns:out143="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_lobupdateallinput"
    xmlns:out142="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_policy_detailbatchresult"
    xmlns:out141="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_exception_histupdateallinputbg"
    xmlns:out146="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_exception_histlistbg"
    xmlns:out145="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticketbatchresult"
    xmlns:out39="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_receipt_detaillist"
    xmlns:out35="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_approverlist"
    xmlns:out36="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticketlistbg"
    xmlns:out37="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_jobslist"
    xmlns:out38="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_approverbg"
    xmlns:out32="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_approverlistbg"
    xmlns:out31="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_app_configlist"
    xmlns:out34="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_receipt_detailcontainer"
    xmlns:out33="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_insuredbg"
    xmlns:out30="http://com/ibm/j2ca/fault/afcfault"
    xmlns:out11="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_receipt_detailupdateallinputbg"
    xmlns:out12="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_documentsupdateallinputbg"
    xmlns:out10="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_app_configlistbg"
    xmlns:out101="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_approvercontainer"
    xmlns:out102="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_refundbatchresult"
    xmlns:out19="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detail_histlistbg"
    xmlns:out103="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_refundlistbg"
    xmlns:out18="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_insuredupdateallinputbg"
    xmlns:out104="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_jobslistbg"
    xmlns:out17="wsdl.http://Access-ApplicationDB/JDBCImport"
    xmlns:out16="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detail_histbatchresult"
    xmlns:out80="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_reasonupdateallinputbg"
    xmlns:out15="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_document_masterlist"
    xmlns:out81="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detailcontainer"
    xmlns:out14="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_reason"
    xmlns:out100="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_receipt_detailbg"
    xmlns:out13="http://com/ibm/j2ca/fault"
    xmlns:out109="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_option"
    xmlns:out84="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticketlist"
    xmlns:out85="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bulkoperationresult/updateallresult"
    xmlns:out82="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_lobbg"
    xmlns:out83="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detail_histcontainer"
    xmlns:out105="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_exception_histlist"
    xmlns:out88="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detail_histlist"
    xmlns:out106="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_jobsbatchresult"
    xmlns:out89="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detaillist"
    xmlns:out107="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_app_configbg"
    xmlns:out86="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_documentscontainer"
    xmlns:out108="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/existsresult/existsresult"
    xmlns:out87="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detail_histupdateallinput"
    xmlns:out90="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_approver"
    xmlns:out91="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_refundupdateallinputbg"
    xmlns:out92="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_histbg"
    xmlns:out93="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_optionlist"
    xmlns:out94="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_policy_detaillist"
    xmlns:out95="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_document_masterbg"
    xmlns:out96="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_optionbg"
    xmlns:out97="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_refundcontainer"
    xmlns:out98="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_histcontainer"
    xmlns:out99="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_approverupdateallinputbg"
    xmlns:out69="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket"
    xmlns:out68="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_refundlist"
    xmlns:out66="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_approverupdateallinput"
    xmlns:out67="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_optionupdateallinput"
    xmlns:out64="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_policy_detailcontainer"
    xmlns:out65="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_insuredupdateallinput"
    xmlns:out62="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_document_mastercontainer"
    xmlns:out63="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_documentslist"
    xmlns:out60="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_receipt_detail"
    xmlns:out61="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_histupdateallinputbg"
    xmlns:out79="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticketcontainer"
    xmlns:out70="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detail_hist"
    xmlns:out75="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_insured"
    xmlns:out76="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detail_histbg"
    xmlns:out77="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_optionlistbg"
    xmlns:out78="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/documentu32matrixbg"
    xmlns:out71="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_insuredcontainer"
    xmlns:out72="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_exception_hist"
    xmlns:out73="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detail"
    xmlns:out="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detail_histupdateallinputbg"
    xmlns:out74="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/documentu32matrixcontainer"
    xmlns:map="http://Access-ApplicationDB/xslt/input_map_req_1"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="date str exsl set math map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:call-template name="map:input_map_req_12">
              <xsl:with-param name="body" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="body" mode="map:input_map_req_1"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:input_map_req_1">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'in:findAllDocumentsRequestMsg'"/>
      </xsl:attribute>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:input_map_req_12">
    <xsl:param name="body"/>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
