<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/output_map_res_1.map" md5sum="834ecf70ec7b97dd6aadd020f2503078" version="8.0.501" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM Graphical Data Mapping Editor.
*   Version 8.0.5.0
*
*   Mapping file:		output_map_res_1.map
*   Map declaration(s):	output_map_res_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FAccess-ApplicationDB%252FJDBCImport%257DretrieveRefundRas_TicketBGResponseMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FTicketDomain-v1.0.0%252FRetrieveTicket%257DfindTicketDetailResponseMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:str="http://exslt.org/strings"
    xmlns:exsl="http://exslt.org/common"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:in49="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_receipt_detailupdateallinput"
    xmlns:in48="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_lobupdateallinputbg"
    xmlns:in47="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_jobscontainer"
    xmlns:in42="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detaillistbg"
    xmlns:in41="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_policy_detail"
    xmlns:in40="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_refundupdateallinput"
    xmlns:in46="http://www.ibm.com/xmlns/prod/websphere/bo/6.0.0"
    xmlns:in45="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_insuredbatchresult"
    xmlns:in44="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_document_masterbatchresult"
    xmlns:in43="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_lobcontainer"
    xmlns:in37="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_jobslist"
    xmlns:in36="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticketlistbg"
    xmlns:in39="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_receipt_detaillist"
    xmlns:in38="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_approverbg"
    xmlns:in31="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_app_configlist"
    xmlns:in30="http://com/ibm/j2ca/fault/afcfault"
    xmlns:in33="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_insuredbg"
    xmlns:in32="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_approverlistbg"
    xmlns:in35="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_approverlist"
    xmlns:in34="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_receipt_detailcontainer"
    xmlns:in136="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_exception_histbatchresult"
    xmlns:in135="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_exception_histcontainer"
    xmlns:in134="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_reasonupdateallinput"
    xmlns:in133="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_insuredlistbg"
    xmlns:in132="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_policy_detailupdateallinputbg"
    xmlns:in131="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_jobsupdateallinput"
    xmlns:in130="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_document_masterlistbg"
    xmlns:in29="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_refund"
    xmlns:in28="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_histbatchresult"
    xmlns:in27="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_documentsbg"
    xmlns:in26="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_receipt_detailbatchresult"
    xmlns:in25="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_jobsupdateallinputbg"
    xmlns:in24="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_exception_histbg"
    xmlns:in23="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detailbg"
    xmlns:in22="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticketupdateallinput"
    xmlns:in21="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_documents"
    xmlns:in139="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detailbatchresult"
    xmlns:in20="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_policy_detaillistbg"
    xmlns:in137="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_app_config"
    xmlns:in138="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_receipt_detaillistbg"
    xmlns:in145="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticketbatchresult"
    xmlns:in144="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_policy_detailbg"
    xmlns:in146="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_exception_histlistbg"
    xmlns:in141="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_exception_histupdateallinputbg"
    xmlns:in140="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticketupdateallinputbg"
    xmlns:in143="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_lobupdateallinput"
    xmlns:in142="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_policy_detailbatchresult"
    xmlns:in99="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_approverupdateallinputbg"
    xmlns:in98="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_histcontainer"
    xmlns:in97="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_refundcontainer"
    xmlns:in96="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_optionbg"
    xmlns:in95="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_document_masterbg"
    xmlns:in94="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_policy_detaillist"
    xmlns:in19="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detail_histlistbg"
    xmlns:in18="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_insuredupdateallinputbg"
    xmlns:in15="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_document_masterlist"
    xmlns:in14="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_reason"
    xmlns:in17="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detail_histbatchresult"
    xmlns:in16="wsdl.http://Access-ApplicationDB/JDBCImport"
    xmlns:in11="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_receipt_detailupdateallinputbg"
    xmlns:in10="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_app_configlistbg"
    xmlns:in13="http://com/ibm/j2ca/fault"
    xmlns:in12="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_documentsupdateallinputbg"
    xmlns:in116="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_loblistbg"
    xmlns:in115="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_jobsbg"
    xmlns:in118="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_documentsupdateallinput"
    xmlns:in117="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detailupdateallinput"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:in119="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_document_masterupdateallinput"
    xmlns:io4="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:in93="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_optionlist"
    xmlns:in92="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_histbg"
    xmlns:in91="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_refundupdateallinputbg"
    xmlns:in90="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_approver"
    xmlns:in85="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bulkoperationresult/updateallresult"
    xmlns:in86="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_documentscontainer"
    xmlns:in83="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detail_histcontainer"
    xmlns:in84="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticketlist"
    xmlns:in89="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detaillist"
    xmlns:in87="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detail_histupdateallinput"
    xmlns:in88="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detail_histlist"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:in110="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_reasonlist"
    xmlns:in111="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_policy_detailupdateallinput"
    xmlns:in112="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_hist"
    xmlns:in113="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_insuredlist"
    xmlns:in114="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_documentslistbg"
    xmlns:in129="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_histupdateallinput"
    xmlns:in128="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_lob"
    xmlns:in127="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_optionupdateallinputbg"
    xmlns:in126="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_jobs"
    xmlns:in80="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_reasonupdateallinputbg"
    xmlns:in82="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_lobbg"
    xmlns:in81="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detailcontainer"
    xmlns:in72="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_exception_hist"
    xmlns:in73="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detail"
    xmlns:in74="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/documentu32matrixcontainer"
    xmlns:in75="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_insured"
    xmlns:in76="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detail_histbg"
    xmlns:in77="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_optionlistbg"
    xmlns:in78="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/documentu32matrixbg"
    xmlns:in79="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticketcontainer"
    xmlns:in120="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_app_configupdateallinputbg"
    xmlns:in121="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_reasonlistbg"
    xmlns:in124="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_lobbatchresult"
    xmlns:in125="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/documentu32matrix"
    xmlns:in122="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_optioncontainer"
    xmlns:in123="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_app_configupdateallinput"
    xmlns:in71="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_insuredcontainer"
    xmlns:in70="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detail_hist"
    xmlns:in67="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_optionupdateallinput"
    xmlns:in68="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_refundlist"
    xmlns:in65="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_insuredupdateallinput"
    xmlns:in66="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_approverupdateallinput"
    xmlns:in63="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_documentslist"
    xmlns:in64="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_policy_detailcontainer"
    xmlns:in61="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_histupdateallinputbg"
    xmlns:in62="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_document_mastercontainer"
    xmlns:in69="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket"
    xmlns:in2="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_documentsbatchresult"
    xmlns:in109="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_option"
    xmlns:in4="http://Access-ApplicationDB/JDBCImport"
    xmlns:in108="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/existsresult/existsresult"
    xmlns:in3="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_exception_histupdateallinput"
    xmlns:in107="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_app_configbg"
    xmlns:in106="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_jobsbatchresult"
    xmlns:in105="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_jobslistbg"
    xmlns:in104="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_exception_histlist"
    xmlns:in60="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_receipt_detail"
    xmlns:in="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detail_histupdateallinputbg"
    xmlns:io="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:in54="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_app_configcontainer"
    xmlns:in55="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_document_masterupdateallinputbg"
    xmlns:in56="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_reasonbatchresult"
    xmlns:in57="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_app_configbatchresult"
    xmlns:in50="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_histlist"
    xmlns:in51="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_approverbatchresult"
    xmlns:in52="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_reasonbg"
    xmlns:in53="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_loblist"
    xmlns:in102="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_refundbatchresult"
    xmlns:in9="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_refundbg"
    xmlns:in103="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_refundlistbg"
    xmlns:in100="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_receipt_detailbg"
    xmlns:in101="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_approvercontainer"
    xmlns:in5="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_reasoncontainer"
    xmlns:in58="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_cancellation_optionbatchresult"
    xmlns:in6="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_account_detailupdateallinputbg"
    xmlns:in59="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticket_histlistbg"
    xmlns:in7="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_ticketbg"
    xmlns:in8="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refundras_document_master"
    xmlns:out3="http://TicketDomain-v1.0.0/RetrieveTicket"
    xmlns:out2="wsdl.http://TicketDomain-v1.0.0/RetrieveTicket"
    xmlns:out="http://RACASBO"
    xmlns:map="http://Access-ApplicationDB/xslt/output_map_res_1"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="date str exsl set math map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'out2:findTicketDetailResponseMsg'"/>
            </xsl:attribute>
            <xsl:call-template name="map:output_map_res_12">
              <xsl:with-param name="body" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="body" mode="map:output_map_res_1">
        </xsl:apply-templates>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:output_map_res_1">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out2:findTicketDetailResponseMsg'"/>
      </xsl:attribute>
      <out3:findTicketDetailResponse>
        <!-- a structural mapping with no associated source:  to "output"(TicketBO) -->
        <xsl:element name="output">
        </xsl:element>
      </out3:findTicketDetailResponse>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:output_map_res_12">
    <xsl:param name="body"/>
    <out3:findTicketDetailResponse>
      <!-- a structural mapping with no associated source:  to "output"(TicketBO) -->
      <xsl:element name="output">
      </xsl:element>
    </out3:findTicketDetailResponse>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
