<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/output_map_res_2.map" md5sum="8793bfdb5a01c7600d53cec36fc50c97" version="8.0.501" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM Graphical Data Mapping Editor.
*   Version 8.0.5.0
*
*   Mapping file:		output_map_res_2.map
*   Map declaration(s):	output_map_res_2
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FAccess-ApplicationDB%252FDBInterface%257DcreateDboRas_Exception_HistBGResponseMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FTicketDomain-v1.0.0%252FHandleGeneral%257DsaveExceptionResponseMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:str="http://exslt.org/strings"
    xmlns:exsl="http://exslt.org/common"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:in409="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementdraftticketcontainer"
    xmlns:in403="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_productupdateallinputbg"
    xmlns:in404="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updatetransactioncountbg"
    xmlns:in401="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_user_detailsupdateallinputbg"
    xmlns:in402="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_statuscontainer"
    xmlns:in407="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/draftidbg"
    xmlns:in408="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_receipt_detailbg"
    xmlns:in405="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/userdetailscontainer"
    xmlns:in406="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_exception_histlist"
    xmlns:in400="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approval_gridupdateallinputbg"
    xmlns:in="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_service_loggingbg"
    xmlns:io="http://www.w3.org/2005/08/addressing"
    xmlns:in20="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_policy_detailcontainer"
    xmlns:in22="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_report_accessbatchresult"
    xmlns:in21="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_lobupdateallinputbg"
    xmlns:in24="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_histlistbg"
    xmlns:in23="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_error_code_master"
    xmlns:in26="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_statuslistbg"
    xmlns:in25="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_optioncontainer"
    xmlns:in28="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_holiday_schedulelistbg"
    xmlns:in27="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detail_histbg"
    xmlns:in29="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_draft_ticket"
    xmlns:in197="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_histupdateallinputbg"
    xmlns:in198="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bopschannelntidconfigcontainer"
    xmlns:in195="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_loblistbg"
    xmlns:in196="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_service_loggingbatchresult"
    xmlns:in11="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bulk_file_loglist"
    xmlns:in10="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/cancellationoptioncontainer"
    xmlns:in13="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_reverse_feed_status_masterupdateallinputbg"
    xmlns:in199="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_insuredupdateallinputbg"
    xmlns:in12="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ticketdetailspolicynocontainer"
    xmlns:in15="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_transactionbg"
    xmlns:in14="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementdraftidbg"
    xmlns:in190="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_uploaded_filebatchresult"
    xmlns:in17="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_reverse_feedlistbg"
    xmlns:in16="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ticketdetailspolicynoapplicationno"
    xmlns:in19="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_servicelistbg"
    xmlns:in193="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_serviceupdateallinputbg"
    xmlns:in18="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_servicebatchresult"
    xmlns:in194="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_app_configlistbg"
    xmlns:in191="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bops_channel_ntid_configupdateallinputbg"
    xmlns:in192="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_document_masterupdateallinputbg"
    xmlns:in40="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_draftcontainer"
    xmlns:in186="wsdl.http://Access-ApplicationDB/DBInterface"
    xmlns:in187="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticketbg"
    xmlns:in42="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bulk_file_logupdateallinput"
    xmlns:in184="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/draftid"
    xmlns:in41="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_scheduler_statuslist"
    xmlns:in185="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateticketstatusbg"
    xmlns:in44="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/draftticketid"
    xmlns:in43="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_error_code_masterbg"
    xmlns:in46="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/appconfigcontainer"
    xmlns:in188="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_exception_histupdateallinput"
    xmlns:in45="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refund"
    xmlns:in189="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bops_channel_ntid_configlist"
    xmlns:in48="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updatepolicydetails"
    xmlns:in47="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bankdetailscontainer"
    xmlns:in49="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementlobproductbg"
    xmlns:in182="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_work_schedulecontainer"
    xmlns:in183="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_draftlistbg"
    xmlns:in180="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_scheduler_statusupdateallinput"
    xmlns:in181="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/reversefeedstatusbg"
    xmlns:in175="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detailbg"
    xmlns:in296="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementproductcode"
    xmlns:in176="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/documentmatrixbg"
    xmlns:in297="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bops_channel_ntid_configbg"
    xmlns:in31="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/policydetailspolicynocertificatenobg"
    xmlns:in173="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detail_histlistbg"
    xmlns:in294="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_reverse_feedupdateallinputbg"
    xmlns:in30="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/productbg"
    xmlns:in174="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_jobsupdateallinputbg"
    xmlns:in295="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_service_logginglist"
    xmlns:in33="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_policy_detaillistbg"
    xmlns:in179="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_receipt_detailupdateallinputbg"
    xmlns:in32="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bankdetailsbg"
    xmlns:in35="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticketcontainer"
    xmlns:in177="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_user_detailsbatchresult"
    xmlns:in298="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_jobslist"
    xmlns:in34="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_reasonbg"
    xmlns:in178="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_draft_ticketlistbg"
    xmlns:in299="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_service_logginglistbg"
    xmlns:in37="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_report_accesslist"
    xmlns:in36="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_work_schedulelistbg"
    xmlns:in39="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateaccountdetails"
    xmlns:in38="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket"
    xmlns:in171="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_policy_detailbg"
    xmlns:in292="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_app_configupdateallinput"
    xmlns:in172="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_draftupdateallinput"
    xmlns:in293="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_user_detailslist"
    xmlns:in290="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_histupdateallinput"
    xmlns:in170="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_reasoncontainer"
    xmlns:in291="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_valid_proposal_statuslist"
    xmlns:in71="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_draft_ticketbg"
    xmlns:in70="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateticketdetailstatus"
    xmlns:in62="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_report_access"
    xmlns:in164="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approverbatchresult"
    xmlns:in285="http://Access-ApplicationDB/DBInterface"
    xmlns:in61="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_holiday_schedulebg"
    xmlns:in165="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/gctransactiondetailsbg"
    xmlns:in286="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_receipt_detail"
    xmlns:in64="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_report_accessupdateallinputbg"
    xmlns:in162="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/cancellationreasonbg"
    xmlns:in283="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateticketdetailstatusbg"
    xmlns:in63="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/productcontainer"
    xmlns:in163="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticketlistbg"
    xmlns:in284="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_draftlist"
    xmlns:in66="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_work_schedule"
    xmlns:in168="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ticketdetailsreceiptno"
    xmlns:in289="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refund_histupdateallinputbg"
    xmlns:in65="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementlobbg"
    xmlns:in169="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_error_code_masterupdateallinputbg"
    xmlns:in68="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/policydetailspolicynoproposalnocontainer"
    xmlns:in166="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticketlist"
    xmlns:in287="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_receipt_detaillistbg"
    xmlns:in67="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_holiday_scheduleupdateallinput"
    xmlns:in167="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detaillistbg"
    xmlns:in288="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_icrm_service_responsebg"
    xmlns:in69="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/reversefeedidbg"
    xmlns:in160="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_exception_histupdateallinputbg"
    xmlns:in281="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_uploaded_filebg"
    xmlns:in161="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_user_detailslistbg"
    xmlns:in282="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ccmrequestidbg"
    xmlns:in280="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_status"
    xmlns:in159="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refundlistbg"
    xmlns:in60="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/policydetailspolicynoproposalnobg"
    xmlns:in51="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_productlistbg"
    xmlns:in153="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_holiday_schedulebatchresult"
    xmlns:in274="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_documentscontainer"
    xmlns:in395="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateinsureddetailsbg"
    xmlns:in50="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_valid_proposal_statuslistbg"
    xmlns:in154="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/gctransactionidcontainer"
    xmlns:in275="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refunddetails"
    xmlns:in396="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_uploaded_filelist"
    xmlns:in53="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_servicecontainer"
    xmlns:in151="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approval_gridlistbg"
    xmlns:in272="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_error_code_mastercontainer"
    xmlns:in393="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateexcessrefundreversefeedbg"
    xmlns:in52="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ccmrequestidcontainer"
    xmlns:in152="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updatenegativeendorsementdraftticketdetails"
    xmlns:in273="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/insureddetailscontainer"
    xmlns:in394="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bank_detailslistbg"
    xmlns:in55="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_exception_histbg"
    xmlns:in157="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/policydetails"
    xmlns:in278="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementdraftticket"
    xmlns:in399="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_document_masterlist"
    xmlns:in54="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bank_details"
    xmlns:in158="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_user_details"
    xmlns:in279="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ticketdetailspolicynobg"
    xmlns:in57="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_work_scheduleupdateallinput"
    xmlns:in155="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/lobcontainer"
    xmlns:in276="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refund_histcontainer"
    xmlns:in397="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/reversefeedstatuscontainer"
    xmlns:in56="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_policy_detailupdateallinput"
    xmlns:in156="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateappcongfigslno"
    xmlns:in277="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/draftnobg"
    xmlns:in398="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_optionbatchresult"
    xmlns:in59="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_app_configbatchresult"
    xmlns:in58="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateexcessrefunddraftidbg"
    xmlns:in270="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detail_histupdateallinputbg"
    xmlns:in391="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_reverse_feed_status_masterupdateallinput"
    xmlns:in150="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_optionlist"
    xmlns:in271="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_error_code_masterbatchresult"
    xmlns:in392="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_transactionlistbg"
    xmlns:in390="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_app_configupdateallinputbg"
    xmlns:in148="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/draftticketcontainer"
    xmlns:in269="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_draftbatchresult"
    xmlns:in149="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approval_gridcontainer"
    xmlns:in91="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/lob"
    xmlns:in90="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_transaction"
    xmlns:in93="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_valid_proposal_statusbatchresult"
    xmlns:in92="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_transactionupdateallinputbg"
    xmlns:in84="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/documentmatrix"
    xmlns:in142="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/policydetailspolicynolannocontainer"
    xmlns:in263="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_draft"
    xmlns:in384="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_servicelist"
    xmlns:in83="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/existsresult/existsresult"
    xmlns:in143="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_app_configlist"
    xmlns:in264="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementlobproduct"
    xmlns:in385="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/draftticketidcontainer"
    xmlns:in86="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/draftno"
    xmlns:in140="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bops_channel_ntid_config"
    xmlns:in261="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approval_gridbg"
    xmlns:in382="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/policydetailspolicynoproposalno"
    xmlns:in85="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementdraftnocontainer"
    xmlns:in141="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_jobsbg"
    xmlns:in262="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ticketdetailspolicynoapplicationnocontainer"
    xmlns:in383="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateaccountdetailsbg"
    xmlns:in88="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_transactionupdateallinput"
    xmlns:in146="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/policydetailscontainer"
    xmlns:in267="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementproductnamebg"
    xmlns:in388="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_documentsbatchresult"
    xmlns:in87="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateticketstatus"
    xmlns:in147="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_app_configcontainer"
    xmlns:in268="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_receipt_detailupdateallinput"
    xmlns:in389="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementlobproductcontainer"
    xmlns:in144="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updatepolicydetailsbg"
    xmlns:in265="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_insuredupdateallinput"
    xmlns:in386="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_holiday_schedulelist"
    xmlns:in89="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approver"
    xmlns:in145="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_valid_proposal_statusbg"
    xmlns:in266="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementlob"
    xmlns:in387="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/cancellationreasoncontainer"
    xmlns:in380="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_draft_ticketupdateallinputbg"
    xmlns:in260="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/lobbg"
    xmlns:in381="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detail_histcontainer"
    xmlns:in139="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/userdetails"
    xmlns:in137="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updategctransactiondetails"
    xmlns:in258="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ticketdetailscontainer"
    xmlns:in379="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/receiptdetails"
    xmlns:in138="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/draftticketbg"
    xmlns:in259="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ticketdetailspolicynoapplicationnobg"
    xmlns:in80="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updatereceiptdetails"
    xmlns:in82="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_scheduler_statuscontainer"
    xmlns:in81="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refund_histbg"
    xmlns:in73="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateexcessrefundservice"
    xmlns:in131="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_histbg"
    xmlns:in252="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_valid_proposal_statusupdateallinput"
    xmlns:in373="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refund_histupdateallinput"
    xmlns:in494="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detailcontainer"
    xmlns:in72="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_statuslist"
    xmlns:in132="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateccmtransactiondeatils"
    xmlns:in253="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/serviceid"
    xmlns:in374="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementproductcodebg"
    xmlns:in495="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refundbatchresult"
    xmlns:in75="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_statusbatchresult"
    xmlns:in250="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateticketdetailsbg"
    xmlns:in371="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_scheduler_statusbatchresult"
    xmlns:in492="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/policydetailspolicynolannobg"
    xmlns:in74="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_productbg"
    xmlns:in130="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_optionlistbg"
    xmlns:in251="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_user_detailscontainer"
    xmlns:in372="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementloggingidbg"
    xmlns:in493="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refundupdateallinput"
    xmlns:in77="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/appconfigbg"
    xmlns:in135="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_policy_detailbatchresult"
    xmlns:in256="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_reverse_feed_status_master"
    xmlns:in377="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_scheduler_statusupdateallinputbg"
    xmlns:in498="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/reversefeedbg"
    xmlns:in76="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bulk_file_logcontainer"
    xmlns:in136="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/cancellationoptionbg"
    xmlns:in257="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateccmtransactiondeatilsbg"
    xmlns:in378="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/insureddetailsbg"
    xmlns:in79="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateexcessrefunddraftid"
    xmlns:in133="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_jobslistbg"
    xmlns:in254="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_lobcontainer"
    xmlns:in375="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/accountdetailscontainer"
    xmlns:in496="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refund_histlistbg"
    xmlns:in78="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_optionbg"
    xmlns:in134="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_work_schedulebg"
    xmlns:in255="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_documentsupdateallinputbg"
    xmlns:in376="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/policydetailspolicynocertificatenocontainer"
    xmlns:in497="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_lob"
    xmlns:in490="http://com/ibm/j2ca/fault/afcfault"
    xmlns:in370="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/gctransactiondetailscontainer"
    xmlns:in491="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_draft_ticketcontainer"
    xmlns:in128="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_user_detailsupdateallinput"
    xmlns:in249="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementdraftticketbg"
    xmlns:in129="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bopschannelntidconfigbg"
    xmlns:in126="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_masterupdateallinputbg"
    xmlns:in247="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_document_masterupdateallinput"
    xmlns:in368="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bops_channel_ntid_configlistbg"
    xmlns:in489="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_service"
    xmlns:in127="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_reverse_feed_status_masterbg"
    xmlns:in248="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ticketdetailsbg"
    xmlns:in369="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementdraftidcontainer"
    xmlns:in120="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_reverse_feed"
    xmlns:in241="http://com/ibm/j2ca/fault"
    xmlns:in362="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_reverse_feed_status_masterbatchresult"
    xmlns:in483="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_reasonupdateallinputbg"
    xmlns:in121="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_icrm_service_responseupdateallinputbg"
    xmlns:in242="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_reason"
    xmlns:in363="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_service_loggingupdateallinputbg"
    xmlns:in484="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_insuredcontainer"
    xmlns:in360="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_statusupdateallinputbg"
    xmlns:in481="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_receipt_detailbatchresult"
    xmlns:in240="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bulk_file_logbatchresult"
    xmlns:in361="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_insuredbatchresult"
    xmlns:in482="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/appconfig"
    xmlns:in124="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_statusupdateallinput"
    xmlns:in245="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bulk_file_loglistbg"
    xmlns:in366="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_histcontainer"
    xmlns:in487="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approvercontainer"
    xmlns:in125="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updaterefunddetails"
    xmlns:in246="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_draft_ticketupdateallinput"
    xmlns:in367="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bank_detailsupdateallinput"
    xmlns:in488="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_statusbg"
    xmlns:in122="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_reverse_feedcontainer"
    xmlns:in243="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_lobupdateallinput"
    xmlns:in364="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_report_accesscontainer"
    xmlns:in485="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateappcongfigslnobg"
    xmlns:in123="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_optionupdateallinput"
    xmlns:in244="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_error_code_masterlistbg"
    xmlns:in365="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementproductname"
    xmlns:in486="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detail"
    xmlns:in480="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_policy_detaillist"
    xmlns:in117="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bulk_file_log"
    xmlns:in238="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementloggingidcontainer"
    xmlns:in359="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_app_config"
    xmlns:in118="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_icrm_service_responsebatchresult"
    xmlns:in239="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ccmrequestid"
    xmlns:in115="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateinsureddetails"
    xmlns:in236="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ticketdetailspolicyno"
    xmlns:in357="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/gctransactiondetails"
    xmlns:in478="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_icrm_service_responsecontainer"
    xmlns:in116="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bulk_file_logbg"
    xmlns:in237="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_reasonlistbg"
    xmlns:in358="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateexcessrefundservicebg"
    xmlns:in479="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementproductcodecontainer"
    xmlns:in119="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_reasonlist"
    xmlns:in95="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_draftbg"
    xmlns:in230="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refund_histlist"
    xmlns:in351="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/reversefeedstatus"
    xmlns:in472="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_valid_proposal_statusupdateallinputbg"
    xmlns:in94="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_exception_histlistbg"
    xmlns:in110="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_insuredlistbg"
    xmlns:in231="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_exception_hist"
    xmlns:in352="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_holiday_schedulecontainer"
    xmlns:in473="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_productcontainer"
    xmlns:in97="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refundbg"
    xmlns:in470="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementdraftid"
    xmlns:in96="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/policydetailsbg"
    xmlns:in350="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ticketdetails"
    xmlns:in471="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bankdetails"
    xmlns:in99="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_serviceupdateallinput"
    xmlns:in113="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/reversefeed"
    xmlns:in234="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_receipt_detaillist"
    xmlns:in355="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_document_master"
    xmlns:in476="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/policydetailspolicynocertificateno"
    xmlns:in98="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementproductnamecontainer"
    xmlns:in114="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/reversefeedidcontainer"
    xmlns:in235="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_holiday_scheduleupdateallinputbg"
    xmlns:in356="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_document_masterbg"
    xmlns:in477="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_reverse_feed_status_masterlist"
    xmlns:in111="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateticketdetails"
    xmlns:in232="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approverlistbg"
    xmlns:in353="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refundlist"
    xmlns:in474="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/accountdetailsbg"
    xmlns:in112="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementmastercontainer"
    xmlns:in233="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bank_detailscontainer"
    xmlns:in354="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detail_histupdateallinput"
    xmlns:in475="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_report_accessbg"
    xmlns:in106="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateappconfig"
    xmlns:in227="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/draftidcontainer"
    xmlns:in348="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/gctransactionidbg"
    xmlns:in469="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateexcessrefunddraftbg"
    xmlns:in107="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_masterlistbg"
    xmlns:in228="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/userdetailsbg"
    xmlns:in349="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refund_hist"
    xmlns:in104="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_reasonupdateallinput"
    xmlns:in225="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_documentslist"
    xmlns:in346="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detailupdateallinputbg"
    xmlns:in467="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_error_code_masterupdateallinput"
    xmlns:in105="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/serviceidbg"
    xmlns:in226="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticketupdateallinput"
    xmlns:in347="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_app_configbg"
    xmlns:in468="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateappconfigbg"
    xmlns:in108="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/receiptdetailsbg"
    xmlns:in229="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detail_histlist"
    xmlns:in109="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detailupdateallinput"
    xmlns:in340="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/draftticket"
    xmlns:in461="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bops_channel_ntid_configbatchresult"
    xmlns:in220="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_product"
    xmlns:in341="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updategctransactiondetailsbg"
    xmlns:in462="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bank_detailsbatchresult"
    xmlns:in460="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_valid_proposal_statuscontainer"
    xmlns:in102="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_documentslistbg"
    xmlns:in223="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bank_detailslist"
    xmlns:in344="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approverupdateallinputbg"
    xmlns:in465="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detaillist"
    xmlns:in103="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/reversefeedid"
    xmlns:in224="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_reverse_feed_status_mastercontainer"
    xmlns:in345="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ticketdetailsreceiptnocontainer"
    xmlns:in466="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/ticketdetailsreceiptnobg"
    xmlns:in100="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_receipt_detailcontainer"
    xmlns:in221="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_masterupdateallinput"
    xmlns:in342="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approval_gridupdateallinput"
    xmlns:in463="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticketupdateallinputbg"
    xmlns:in101="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_draft_ticketlist"
    xmlns:in222="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_histbatchresult"
    xmlns:in343="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refunddetailscontainer"
    xmlns:in464="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_reverse_feedbg"
    xmlns:in216="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_lobbatchresult"
    xmlns:in337="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_service_logging"
    xmlns:in458="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_histlist"
    xmlns:in217="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approverupdateallinput"
    xmlns:in338="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_masterbatchresult"
    xmlns:in459="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/refunddetailsbg"
    xmlns:in214="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_masterbg"
    xmlns:in335="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementdraftno"
    xmlns:in456="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_productbatchresult"
    xmlns:in215="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_user_detailsbg"
    xmlns:in336="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_exception_histcontainer"
    xmlns:in457="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementmaster"
    xmlns:in218="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updatedrafterrordetailsbg"
    xmlns:in339="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_insuredbg"
    xmlns:in219="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_servicebg"
    xmlns:in450="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_uploaded_filecontainer"
    xmlns:in330="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_scheduler_status"
    xmlns:in451="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_loblist"
    xmlns:in212="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_hist"
    xmlns:in333="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refund_histbatchresult"
    xmlns:in454="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticketbatchresult"
    xmlns:in213="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/insureddetails"
    xmlns:in334="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/serviceidcontainer"
    xmlns:in455="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_reverse_feedlist"
    xmlns:in210="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_policy_detailupdateallinputbg"
    xmlns:in331="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateexcessrefundreversefeed"
    xmlns:in452="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updaterefunddetailsbg"
    xmlns:in211="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updatedrafterrordetails"
    xmlns:in332="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detail_histbatchresult"
    xmlns:in453="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_transactionbatchresult"
    xmlns:in205="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_service_loggingcontainer"
    xmlns:in326="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_scheduler_statusbg"
    xmlns:in447="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approverbg"
    xmlns:in206="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approverlist"
    xmlns:in327="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_insured"
    xmlns:in448="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/documentmatrixcontainer"
    xmlns:in203="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approval_gridbatchresult"
    xmlns:in324="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_productupdateallinput"
    xmlns:in445="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_documents"
    xmlns:in204="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bulk_file_logupdateallinputbg"
    xmlns:in325="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updateexcessrefunddraft"
    xmlns:in446="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approval_gridlist"
    xmlns:in209="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_masterlist"
    xmlns:in207="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_productlist"
    xmlns:in328="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_policy_detail"
    xmlns:in449="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_document_masterbatchresult"
    xmlns:in208="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementmasterbg"
    xmlns:in329="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_icrm_service_responselistbg"
    xmlns:in440="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bops_channel_ntid_configcontainer"
    xmlns:in201="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_approval_grid"
    xmlns:in322="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_work_schedulelist"
    xmlns:in443="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updatenegativeendorsementserviceloggingbg"
    xmlns:in202="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bank_detailsbg"
    xmlns:in323="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_jobsupdateallinput"
    xmlns:in444="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_icrm_service_responselist"
    xmlns:in320="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/accountdetails"
    xmlns:in441="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_reverse_feed_status_masterlistbg"
    xmlns:in200="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_valid_proposal_status"
    xmlns:in321="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_transactionlist"
    xmlns:in442="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_reverse_feedbatchresult"
    xmlns:in315="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_draft_ticketbatchresult"
    xmlns:in436="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_uploaded_file"
    xmlns:in316="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_work_scheduleupdateallinputbg"
    xmlns:in437="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_mastercontainer"
    xmlns:in313="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/product"
    xmlns:in434="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bulkoperationresult/updateallresult"
    xmlns:in314="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_work_schedulebatchresult"
    xmlns:in435="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_negative_endorsement_service_loggingupdateallinput"
    xmlns:in2="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementloggingid"
    xmlns:in319="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_uploaded_fileupdateallinputbg"
    xmlns:in4="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_gc_transactioncontainer"
    xmlns:in317="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_jobs"
    xmlns:in438="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_document_masterlistbg"
    xmlns:in3="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_master"
    xmlns:in318="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refundupdateallinputbg"
    xmlns:in439="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bank_detailsupdateallinputbg"
    xmlns:in6="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detail_hist"
    xmlns:in5="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/cancellationreason"
    xmlns:in8="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_report_accessupdateallinput"
    xmlns:in7="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/receiptdetailscontainer"
    xmlns:in311="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_draftupdateallinputbg"
    xmlns:in432="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_holiday_schedule"
    xmlns:in9="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_icrm_service_response"
    xmlns:in312="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/policydetailspolicynolanno"
    xmlns:in433="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_scheduler_statuslistbg"
    xmlns:in430="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/gctransactionid"
    xmlns:in310="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_account_detailbatchresult"
    xmlns:in431="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_optionupdateallinputbg"
    xmlns:in304="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_jobsbatchresult"
    xmlns:in425="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updatenegativeendorsementdraftticketdetailsbg"
    xmlns:in305="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_option"
    xmlns:in426="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updatetransactioncount"
    xmlns:in302="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/reversefeedcontainer"
    xmlns:in423="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_lobbg"
    xmlns:in303="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_document_mastercontainer"
    xmlns:in424="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementdraftnobg"
    xmlns:io3="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:in308="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_exception_histbatchresult"
    xmlns:in429="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_refundcontainer"
    xmlns:io2="http://www.w3.org/2003/05/soap-envelope"
    xmlns:in309="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_excess_refund_reverse_feedupdateallinput"
    xmlns:in306="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_uploaded_filelistbg"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:in427="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_uploaded_fileupdateallinput"
    xmlns:io4="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:in307="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_cancellation_reasonbatchresult"
    xmlns:in428="http://www.ibm.com/xmlns/prod/websphere/bo/6.0.0"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:in300="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/draftnocontainer"
    xmlns:in421="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_insuredlist"
    xmlns:in301="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_jobscontainer"
    xmlns:in422="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_report_accesslistbg"
    xmlns:in420="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_icrm_service_responseupdateallinput"
    xmlns:in414="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/negativeendorsementlobcontainer"
    xmlns:in415="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/cancellationoption"
    xmlns:in412="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_documentsbg"
    xmlns:in413="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/bopschannelntidconfig"
    xmlns:in418="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_error_code_masterlist"
    xmlns:in419="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/draftticketidbg"
    xmlns:in416="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updatereceiptdetailsbg"
    xmlns:in417="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_bops_channel_ntid_configupdateallinput"
    xmlns:in410="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dboras_ticket_documentsupdateallinput"
    xmlns:in411="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updatenegativeendorsementservicelogging"
    xmlns:out2="http://RACASBO"
    xmlns:out3="wsdl.http://TicketDomain-v1.0.0/HandleGeneral"
    xmlns:out="http://TicketDomain-v1.0.0/HandleGeneral"
    xmlns:map="http://RASAccess-ApplicationDB/xslt/output_map_res_2"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="date str exsl set math map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'out3:saveExceptionResponseMsg'"/>
            </xsl:attribute>
            <xsl:call-template name="map:output_map_res_22">
              <xsl:with-param name="body" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="body" mode="map:output_map_res_2">
        </xsl:apply-templates>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:output_map_res_2">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out3:saveExceptionResponseMsg'"/>
      </xsl:attribute>
      <out:saveExceptionResponse>
        <output>
          <!-- a simple data mapping: "in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/ticket_id"(int) to "out2:ticket_id"(double) -->
          <xsl:if test="in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/ticket_id">
            <xsl:element name="out2:ticket_id">
              <xsl:value-of select="in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/ticket_id"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/step"(string) to "out2:step"(string) -->
          <xsl:if test="in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/step">
            <xsl:element name="out2:step">
              <xsl:value-of select="in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/step"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/service"(string) to "out2:service"(string) -->
          <xsl:if test="in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/service">
            <xsl:element name="out2:service">
              <xsl:value-of select="in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/service"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/error_code"(string) to "out2:error_code"(string) -->
          <xsl:if test="in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/error_code">
            <xsl:element name="out2:error_code">
              <xsl:value-of select="in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/error_code"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/error_data"(string) to "out2:error_data"(string) -->
          <xsl:if test="in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/error_data">
            <xsl:element name="out2:error_data">
              <xsl:value-of select="in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/error_data"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/completed_by"(string) to "out2:completed_by"(string) -->
          <xsl:if test="in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/completed_by">
            <xsl:element name="out2:completed_by">
              <xsl:value-of select="in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/completed_by"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/completed_on"(dateTime) to "out2:completed_on"(dateTime) -->
          <xsl:if test="in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/completed_on">
            <xsl:element name="out2:completed_on">
              <xsl:value-of select="in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/completed_on"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/id"(int) to "out2:id"(double) -->
          <xsl:if test="in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/id">
            <xsl:element name="out2:id">
              <xsl:value-of select="in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/id"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/request"(string) to "out2:request"(string) -->
          <xsl:if test="in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/request">
            <xsl:element name="out2:request">
              <xsl:value-of select="in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/request"/>
            </xsl:element>
          </xsl:if>
        </output>
      </out:saveExceptionResponse>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:output_map_res_22">
    <xsl:param name="body"/>
    <out:saveExceptionResponse>
      <output>
        <!-- a simple data mapping: "$body/in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/ticket_id"(int) to "out2:ticket_id"(double) -->
        <xsl:if test="$body/in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/ticket_id">
          <xsl:element name="out2:ticket_id">
            <xsl:value-of select="$body/in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/ticket_id"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$body/in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/step"(string) to "out2:step"(string) -->
        <xsl:if test="$body/in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/step">
          <xsl:element name="out2:step">
            <xsl:value-of select="$body/in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/step"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$body/in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/service"(string) to "out2:service"(string) -->
        <xsl:if test="$body/in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/service">
          <xsl:element name="out2:service">
            <xsl:value-of select="$body/in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/service"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$body/in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/error_code"(string) to "out2:error_code"(string) -->
        <xsl:if test="$body/in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/error_code">
          <xsl:element name="out2:error_code">
            <xsl:value-of select="$body/in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/error_code"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$body/in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/error_data"(string) to "out2:error_data"(string) -->
        <xsl:if test="$body/in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/error_data">
          <xsl:element name="out2:error_data">
            <xsl:value-of select="$body/in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/error_data"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$body/in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/completed_by"(string) to "out2:completed_by"(string) -->
        <xsl:if test="$body/in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/completed_by">
          <xsl:element name="out2:completed_by">
            <xsl:value-of select="$body/in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/completed_by"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$body/in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/completed_on"(dateTime) to "out2:completed_on"(dateTime) -->
        <xsl:if test="$body/in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/completed_on">
          <xsl:element name="out2:completed_on">
            <xsl:value-of select="$body/in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/completed_on"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$body/in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/id"(int) to "out2:id"(double) -->
        <xsl:if test="$body/in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/id">
          <xsl:element name="out2:id">
            <xsl:value-of select="$body/in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/id"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$body/in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/request"(string) to "out2:request"(string) -->
        <xsl:if test="$body/in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/request">
          <xsl:element name="out2:request">
            <xsl:value-of select="$body/in285:createDboRas_Exception_HistBGResponse/in285:createDboRas_Exception_HistBGOutput/DboRas_Exception_Hist/request"/>
          </xsl:element>
        </xsl:if>
      </output>
    </out:saveExceptionResponse>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
